name: Build and Test

on:
  pull_request:
    branches: [ "dev", "prod" ]

jobs:
  build_and_test:
    if: >
      !startsWith(github.head_ref, 'chore(prod): release')
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24.3'
        
    - name: Verify dependencies
      run: go mod verify

    - name: Install dependencies
      run: go mod tidy

    - name: Build
      run: go build -v ./...
      
    - name: Run go vet
      run: go vet ./...
      
    - name: Run lint
      run: go run github.com/golangci/golangci-lint/cmd/golangci-lint@latest run --exclude=testhelpers

    - name: Run staticcheck
      run: go run honnef.co/go/tools/cmd/staticcheck@latest ./...

    - name: Run security audit
      run: go run github.com/securego/gosec/v2/cmd/gosec@latest --exclude-dir=internal/testhelpers ./...

    - name: Test
      run: go test -v ./...

